package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emails generated by hbm2java
 */
@Entity
@Table(name="emails"
    ,schema="dbo"
    ,catalog="mirai"
)
public class Emails  implements java.io.Serializable {


     private int id;
     private Users users;
     private String verificationToken;
     private Date expiredAt;
     private Date updatedAt;
     private Date createdAt;

    public Emails() {
    }

	
    public Emails(int id) {
        this.id = id;
    }
    public Emails(int id, Users users, String verificationToken, Date expiredAt, Date updatedAt, Date createdAt) {
       this.id = id;
       this.users = users;
       this.verificationToken = verificationToken;
       this.expiredAt = expiredAt;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="verification_token")
    public String getVerificationToken() {
        return this.verificationToken;
    }
    
    public void setVerificationToken(String verificationToken) {
        this.verificationToken = verificationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expired_at", length=23)
    public Date getExpiredAt() {
        return this.expiredAt;
    }
    
    public void setExpiredAt(Date expiredAt) {
        this.expiredAt = expiredAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=23)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=23)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


