package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periods generated by hbm2java
 */
@Entity
@Table(name="periods"
    ,schema="dbo"
    ,catalog="mirai"
)
public class Periods  implements java.io.Serializable {


     private int id;
     private Double score;
     private Date date;
     private Set<UsersProjectsPeriods> usersProjectsPeriodses = new HashSet<UsersProjectsPeriods>(0);

    public Periods() {
    }

	
    public Periods(int id) {
        this.id = id;
    }
    public Periods(int id, Double score, Date date, Set<UsersProjectsPeriods> usersProjectsPeriodses) {
       this.id = id;
       this.score = score;
       this.date = date;
       this.usersProjectsPeriodses = usersProjectsPeriodses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="score", precision=53, scale=0)
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periods")
    public Set<UsersProjectsPeriods> getUsersProjectsPeriodses() {
        return this.usersProjectsPeriodses;
    }
    
    public void setUsersProjectsPeriodses(Set<UsersProjectsPeriods> usersProjectsPeriodses) {
        this.usersProjectsPeriodses = usersProjectsPeriodses;
    }




}


