package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name="projects"
    ,schema="dbo"
    ,catalog="mirai"
)
public class Projects  implements java.io.Serializable {


     private int id;
     private String title;
     private Serializable description;
     private Date startDate;
     private Date endDate;
     private Long rating;
     private Date updatedAt;
     private Date createdAt;
     private Boolean status;
     private Boolean visibility;
     private Set<UsersProjectsPeriods> usersProjectsPeriodses = new HashSet<UsersProjectsPeriods>(0);
     private Set<Tasks> taskses = new HashSet<Tasks>(0);
     private Set<UsersRolesProjects> usersRolesProjectses = new HashSet<UsersRolesProjects>(0);

    public Projects() {
    }

	
    public Projects(int id) {
        this.id = id;
    }
    public Projects(int id, String title, Serializable description, Date startDate, Date endDate, Long rating, Date updatedAt, Date createdAt, Boolean status, Boolean visibility, Set<UsersProjectsPeriods> usersProjectsPeriodses, Set<Tasks> taskses, Set<UsersRolesProjects> usersRolesProjectses) {
       this.id = id;
       this.title = title;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.rating = rating;
       this.updatedAt = updatedAt;
       this.createdAt = createdAt;
       this.status = status;
       this.visibility = visibility;
       this.usersProjectsPeriodses = usersProjectsPeriodses;
       this.taskses = taskses;
       this.usersRolesProjectses = usersRolesProjectses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", length=23)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=23)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="rating", precision=18, scale=0)
    public Long getRating() {
        return this.rating;
    }
    
    public void setRating(Long rating) {
        this.rating = rating;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=23)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=23)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="visibility")
    public Boolean getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(Boolean visibility) {
        this.visibility = visibility;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<UsersProjectsPeriods> getUsersProjectsPeriodses() {
        return this.usersProjectsPeriodses;
    }
    
    public void setUsersProjectsPeriodses(Set<UsersProjectsPeriods> usersProjectsPeriodses) {
        this.usersProjectsPeriodses = usersProjectsPeriodses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<Tasks> getTaskses() {
        return this.taskses;
    }
    
    public void setTaskses(Set<Tasks> taskses) {
        this.taskses = taskses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<UsersRolesProjects> getUsersRolesProjectses() {
        return this.usersRolesProjectses;
    }
    
    public void setUsersRolesProjectses(Set<UsersRolesProjects> usersRolesProjectses) {
        this.usersRolesProjectses = usersRolesProjectses;
    }




}


