package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,schema="dbo"
    ,catalog="mirai"
)
public class Roles  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<UsersRolesProjects> usersRolesProjectses = new HashSet<UsersRolesProjects>(0);

    public Roles() {
    }

	
    public Roles(int id) {
        this.id = id;
    }
    public Roles(int id, String name, Set<UsersRolesProjects> usersRolesProjectses) {
       this.id = id;
       this.name = name;
       this.usersRolesProjectses = usersRolesProjectses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<UsersRolesProjects> getUsersRolesProjectses() {
        return this.usersRolesProjectses;
    }
    
    public void setUsersRolesProjectses(Set<UsersRolesProjects> usersRolesProjectses) {
        this.usersRolesProjectses = usersRolesProjectses;
    }




}


