package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="dbo"
    ,catalog="mirai"
)
public class Users  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private Boolean gender;
     private String phone;
     private Boolean enable;
     private Boolean visibility;
     private String thumbnail;
     private Date createdAt;
     private Date updatedAt;
     private Set<UsersRolesProjects> usersRolesProjectses = new HashSet<UsersRolesProjects>(0);
     private Set<Emails> emailses = new HashSet<Emails>(0);
     private Set<UsersProjectsPeriods> usersProjectsPeriodses = new HashSet<UsersProjectsPeriods>(0);

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, String firstName, String lastName, String username, String password, Boolean gender, String phone, Boolean enable, Boolean visibility, String thumbnail, Date createdAt, Date updatedAt, Set<UsersRolesProjects> usersRolesProjectses, Set<Emails> emailses, Set<UsersProjectsPeriods> usersProjectsPeriodses) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.gender = gender;
       this.phone = phone;
       this.enable = enable;
       this.visibility = visibility;
       this.thumbnail = thumbnail;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.usersRolesProjectses = usersRolesProjectses;
       this.emailses = emailses;
       this.usersProjectsPeriodses = usersProjectsPeriodses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="first_name", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="username", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="gender")
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="phone", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="enable")
    public Boolean getEnable() {
        return this.enable;
    }
    
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    
    @Column(name="visibility")
    public Boolean getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(Boolean visibility) {
        this.visibility = visibility;
    }

    
    @Column(name="thumbnail")
    public String getThumbnail() {
        return this.thumbnail;
    }
    
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=23)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=23)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<UsersRolesProjects> getUsersRolesProjectses() {
        return this.usersRolesProjectses;
    }
    
    public void setUsersRolesProjectses(Set<UsersRolesProjects> usersRolesProjectses) {
        this.usersRolesProjectses = usersRolesProjectses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Emails> getEmailses() {
        return this.emailses;
    }
    
    public void setEmailses(Set<Emails> emailses) {
        this.emailses = emailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<UsersProjectsPeriods> getUsersProjectsPeriodses() {
        return this.usersProjectsPeriodses;
    }
    
    public void setUsersProjectsPeriodses(Set<UsersProjectsPeriods> usersProjectsPeriodses) {
        this.usersProjectsPeriodses = usersProjectsPeriodses;
    }




}


