package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersProjectsPeriods generated by hbm2java
 */
@Entity
@Table(name="users_projects_periods"
    ,schema="dbo"
    ,catalog="mirai"
)
public class UsersProjectsPeriods  implements java.io.Serializable {


     private UsersProjectsPeriodsId id;
     private Periods periods;
     private Projects projects;
     private Users users;

    public UsersProjectsPeriods() {
    }

    public UsersProjectsPeriods(UsersProjectsPeriodsId id, Periods periods, Projects projects, Users users) {
       this.id = id;
       this.periods = periods;
       this.projects = projects;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="projectId", column=@Column(name="project_id", nullable=false) ), 
        @AttributeOverride(name="periodId", column=@Column(name="period_id", nullable=false) ) } )
    public UsersProjectsPeriodsId getId() {
        return this.id;
    }
    
    public void setId(UsersProjectsPeriodsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="period_id", nullable=false, insertable=false, updatable=false)
    public Periods getPeriods() {
        return this.periods;
    }
    
    public void setPeriods(Periods periods) {
        this.periods = periods;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id", nullable=false, insertable=false, updatable=false)
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


