package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRolesProjects generated by hbm2java
 */
@Entity
@Table(name="users_roles_projects"
    ,schema="dbo"
    ,catalog="mirai"
)
public class UsersRolesProjects  implements java.io.Serializable {


     private UsersRolesProjectsId id;
     private Projects projects;
     private Roles roles;
     private Users users;

    public UsersRolesProjects() {
    }

    public UsersRolesProjects(UsersRolesProjectsId id, Projects projects, Roles roles, Users users) {
       this.id = id;
       this.projects = projects;
       this.roles = roles;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="projectId", column=@Column(name="project_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public UsersRolesProjectsId getId() {
        return this.id;
    }
    
    public void setId(UsersRolesProjectsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id", nullable=false, insertable=false, updatable=false)
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


