package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersProjectsPeriodsId generated by hbm2java
 */
@Embeddable
public class UsersProjectsPeriodsId  implements java.io.Serializable {


     private int userId;
     private int projectId;
     private int periodId;

    public UsersProjectsPeriodsId() {
    }

    public UsersProjectsPeriodsId(int userId, int projectId, int periodId) {
       this.userId = userId;
       this.projectId = projectId;
       this.periodId = periodId;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


    @Column(name="period_id", nullable=false)
    public int getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersProjectsPeriodsId) ) return false;
		 UsersProjectsPeriodsId castOther = ( UsersProjectsPeriodsId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getProjectId()==castOther.getProjectId())
 && (this.getPeriodId()==castOther.getPeriodId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProjectId();
         result = 37 * result + this.getPeriodId();
         return result;
   }   


}


