package mirai;
// Generated Jul 4, 2021 11:39:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesProjectsId generated by hbm2java
 */
@Embeddable
public class UsersRolesProjectsId  implements java.io.Serializable {


     private int projectId;
     private int userId;

    public UsersRolesProjectsId() {
    }

    public UsersRolesProjectsId(int projectId, int userId) {
       this.projectId = projectId;
       this.userId = userId;
    }
   


    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersRolesProjectsId) ) return false;
		 UsersRolesProjectsId castOther = ( UsersRolesProjectsId ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProjectId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


