package com.sbifpt.mirai.web.dto.entity;
// Generated Jun 27, 2021 11:09:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Periods generated by hbm2java
 */
@Entity
@Table(name = "periods")
@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Period implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;
	
	@Column(name = "score", precision = 53, scale = 0)
	private Double score;
	
	@Column(name = "status")
	private String status;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	private Set<UserProjectPeriod> usersProjectsPeriods = new HashSet<UserProjectPeriod>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	private Set<Task> tasks = new HashSet<Task>(0);


}
